<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Project 2: Ames Housing Data and Kaggle Challenge

# Problem Statement

Real estate was once considered a relative safe harbor, an asset class marked by steady value creation and predictable trends. Those days are over. New technologies and urgent sustainability concerns are now disrupting the industry in ways that raise the stakes for every decision real estate investors make.

A real estate investment trust (REITs) that operates and invests in income-producing real estate is looking into adding  properties (particularly housing) in Ames, Iowa into their portfolio. As part of the REITs company's data team, we have been tasked with creating a regression model based on the Ames Housing Dataset collected from 2006 to 2010, to predict prices of houses in Ames.

# Part 1: EDA and Cleaning

## Table of Contents:
- [Background](#Background)
- [Datasets Used for Analysis](#Datasets-Used-for-Analysis)
- [Import Libraries](#Import-Libraries)
- [Data Import & Cleaning](#Data-Import-and-Cleaning)
- [Exploratory Data Analysis](#Exploratory-Data-Analysis)
- [Data Visualization](#Visualize-the-Data)
- [Conclusions and Recommendations](#Conclusions-and-Recommendations)

## Background

Based on a United States Census Bureau report in 2010, Ames, Iowa had a population of approximately 59,000. Also, Ames, Iowa economy and demographics is largely defined by the Iowa State University, a public research university located in the middle of the city. More than 75%  of Ames' population is either studying as a student or working as a faculty at Iowa State University, making Ames one large extended campus (more information at this website). Therefore, it isnâ€™t surprising that Ames's largest employer is Iowa State University, which employed approximately 20% of total employment. Hence, just like many college towns, Ames' real estate market is defined by a substantial proportion of rental properties, explaining the housing market's stability in Ames. ([*source*](https://nycdatascience.com/blog/student-works/predicting-housing-prices-in-ames-iowa-6/))

## Datasets Used for Analysis

There are 2 datasets included in the [`datasets`](../datasets/) folder for this project.

* [`train.csv`](../datasets/train.csv): (2016 - 2010) Ames Housing dataset
* [`test.csv`](../datasets/test.csv): (2016 - 2010) Ames Housing dataset, excluding target variable

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

## Data Import and Cleaning

### Data Import

In [14]:
train = pd.read_csv('../datasets/train.csv')
print(train.head())
print(train.describe())

    Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley  \
0  109  533352170           60        RL           NaN     13517   Pave   NaN
1  544  531379050           60        RL          43.0     11492   Pave   NaN
2  153  535304180           20        RL          68.0      7922   Pave   NaN
3  318  916386060           60        RL          73.0      9802   Pave   NaN
4  255  906425045           50        RL          82.0     14235   Pave   NaN

  Lot Shape Land Contour  ... Screen Porch Pool Area Pool QC Fence  \
0       IR1          Lvl  ...            0         0     NaN   NaN
1       IR1          Lvl  ...            0         0     NaN   NaN
2       Reg          Lvl  ...            0         0     NaN   NaN
3       Reg          Lvl  ...            0         0     NaN   NaN
4       IR1          Lvl  ...            0         0     NaN   NaN

  Misc Feature Misc Val Mo Sold Yr Sold  Sale Type  SalePrice
0          NaN        0       3    2010        WD      130500
1          NaN        0       4    2009        WD      220000
2          NaN        0       1    2010        WD      109000
3          NaN        0       4    2010        WD      174000
4          NaN        0       3    2010        WD      138500

[5 rows x 81 columns]
                Id           PID  MS SubClass  Lot Frontage       Lot Area  \
count  2051.000000  2.051000e+03  2051.000000   1721.000000    2051.000000
mean   1474.033642  7.135900e+08    57.008776     69.055200   10065.208191
std     843.980841  1.886918e+08    42.824223     23.260653    6742.488909
min       1.000000  5.263011e+08    20.000000     21.000000    1300.000000
25%     753.500000  5.284581e+08    20.000000     58.000000    7500.000000
50%    1486.000000  5.354532e+08    50.000000     68.000000    9430.000000
75%    2198.000000  9.071801e+08    70.000000     80.000000   11513.500000
max    2930.000000  9.241520e+08   190.000000    313.000000  159000.000000

       Overall Qual  Overall Cond   Year Built  Year Remod/Add  Mas Vnr Area  \
count   2051.000000   2051.000000  2051.000000     2051.000000   2029.000000
mean       6.112140      5.562165  1971.708922     1984.190151     99.695909
std        1.426271      1.104497    30.177889       21.036250    174.963129
min        1.000000      1.000000  1872.000000     1950.000000      0.000000
25%        5.000000      5.000000  1953.500000     1964.500000      0.000000
50%        6.000000      5.000000  1974.000000     1993.000000      0.000000
75%        7.000000      6.000000  2001.000000     2004.000000    161.000000
max       10.000000      9.000000  2010.000000     2010.000000   1600.000000

       ...  Wood Deck SF  Open Porch SF  Enclosed Porch   3Ssn Porch  \
count  ...   2051.000000    2051.000000     2051.000000  2051.000000
mean   ...     93.833740      47.556802       22.571916     2.591419
std    ...    128.549416      66.747241       59.845110    25.229615
min    ...      0.000000       0.000000        0.000000     0.000000
25%    ...      0.000000       0.000000        0.000000     0.000000
50%    ...      0.000000      27.000000        0.000000     0.000000
75%    ...    168.000000      70.000000        0.000000     0.000000
max    ...   1424.000000     547.000000      432.000000   508.000000

       Screen Porch    Pool Area      Misc Val      Mo Sold      Yr Sold  \
count   2051.000000  2051.000000   2051.000000  2051.000000  2051.000000
mean      16.511458     2.397855     51.574354     6.219893  2007.775719
std       57.374204    37.782570    573.393985     2.744736     1.312014
min        0.000000     0.000000      0.000000     1.000000  2006.000000
25%        0.000000     0.000000      0.000000     4.000000  2007.000000
50%        0.000000     0.000000      0.000000     6.000000  2008.000000
75%        0.000000     0.000000      0.000000     8.000000  2009.000000
max      490.000000   800.000000  17000.000000    12.000000  2010.000000

           SalePrice
count    2051.000000
mean   181469.701609
std     79258.659352
min     12789.000000
25%    129825.000000
50%    162500.000000
75%    214000.000000
max    611657.000000

[8 rows x 39 columns]

In [13]:
print(train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               2051 non-null   int64
 1   PID              2051 non-null   int64
 2   MS SubClass      2051 non-null   int64
 3   MS Zoning        2051 non-null   object
 4   Lot Frontage     1721 non-null   float64
 5   Lot Area         2051 non-null   int64
 6   Street           2051 non-null   object
 7   Alley            140 non-null    object
 8   Lot Shape        2051 non-null   object
 9   Land Contour     2051 non-null   object
 10  Utilities        2051 non-null   object
 11  Lot Config       2051 non-null   object
 12  Land Slope       2051 non-null   object
 13  Neighborhood     2051 non-null   object
 14  Condition 1      2051 non-null   object
 15  Condition 2      2051 non-null   object
 16  Bldg Type        2051 non-null   object
 17  House Style      2051 non-null   object
 18  Overall Qual     2051 non-null   int64
 19  Overall Cond     2051 non-null   int64
 20  Year Built       2051 non-null   int64
 21  Year Remod/Add   2051 non-null   int64
 22  Roof Style       2051 non-null   object
 23  Roof Matl        2051 non-null   object
 24  Exterior 1st     2051 non-null   object
 25  Exterior 2nd     2051 non-null   object
 26  Mas Vnr Type     2029 non-null   object
 27  Mas Vnr Area     2029 non-null   float64
 28  Exter Qual       2051 non-null   object
 29  Exter Cond       2051 non-null   object
 30  Foundation       2051 non-null   object
 31  Bsmt Qual        1996 non-null   object
 32  Bsmt Cond        1996 non-null   object
 33  Bsmt Exposure    1993 non-null   object
 34  BsmtFin Type 1   1996 non-null   object
 35  BsmtFin SF 1     2050 non-null   float64
 36  BsmtFin Type 2   1995 non-null   object
 37  BsmtFin SF 2     2050 non-null   float64
 38  Bsmt Unf SF      2050 non-null   float64
 39  Total Bsmt SF    2050 non-null   float64
 40  Heating          2051 non-null   object
 41  Heating QC       2051 non-null   object
 42  Central Air      2051 non-null   object
 43  Electrical       2051 non-null   object
 44  1st Flr SF       2051 non-null   int64
 45  2nd Flr SF       2051 non-null   int64
 46  Low Qual Fin SF  2051 non-null   int64
 47  Gr Liv Area      2051 non-null   int64
 48  Bsmt Full Bath   2049 non-null   float64
 49  Bsmt Half Bath   2049 non-null   float64
 50  Full Bath        2051 non-null   int64
 51  Half Bath        2051 non-null   int64
 52  Bedroom AbvGr    2051 non-null   int64
 53  Kitchen AbvGr    2051 non-null   int64
 54  Kitchen Qual     2051 non-null   object
 55  TotRms AbvGrd    2051 non-null   int64
 56  Functional       2051 non-null   object
 57  Fireplaces       2051 non-null   int64
 58  Fireplace Qu     1051 non-null   object
 59  Garage Type      1938 non-null   object
 60  Garage Yr Blt    1937 non-null   float64
 61  Garage Finish    1937 non-null   object
 62  Garage Cars      2050 non-null   float64
 63  Garage Area      2050 non-null   float64
 64  Garage Qual      1937 non-null   object
 65  Garage Cond      1937 non-null   object
 66  Paved Drive      2051 non-null   object
 67  Wood Deck SF     2051 non-null   int64
 68  Open Porch SF    2051 non-null   int64
 69  Enclosed Porch   2051 non-null   int64
 70  3Ssn Porch       2051 non-null   int64
 71  Screen Porch     2051 non-null   int64
 72  Pool Area        2051 non-null   int64
 73  Pool QC          9 non-null      object
 74  Fence            400 non-null    object
 75  Misc Feature     65 non-null     object
 76  Misc Val         2051 non-null   int64
 77  Mo Sold          2051 non-null   int64
 78  Yr Sold          2051 non-null   int64
 79  Sale Type        2051 non-null   object
 80  SalePrice        2051 non-null   int64
dtypes: float64(11), int64(28), object(42)
memory usage: 1.3+ MB
None

In [4]:
train

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,1587,921126030,20,RL,79.0,11449,Pave,NaN,IR1,HLS,...,0,0,NaN,NaN,NaN,0,1,2008,WD,298751
2047,785,905377130,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2009,WD,82500
2048,916,909253010,50,RL,57.0,7558,Pave,NaN,Reg,Bnk,...,0,0,NaN,NaN,NaN,0,3,2009,WD,177000
2049,639,535179160,20,RL,80.0,10400,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,11,2009,WD,144000
2050,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,6,2010,WD,189000

In [5]:
print(train.columns)

Index(['Id', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area',
       'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities',
       'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1',
       'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style',
       'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type',
       'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual',
       'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1',
       'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF',
       'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF',
       '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr',
       'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional',
       'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt',
       'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual',
       'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF',
       'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC',
       'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type',
       'SalePrice'],
      dtype='object')

In [6]:
train['Yr Sold'].min()

2006